TemplateURL: BUCKET_URL_PLACEHOLDER/parallelcluster-ui.yaml
Parameters:
  - ParameterKey: AdminUserEmail
    UsePreviousValue: true
  - ParameterKey: Version
    ParameterValue: 3.8.0
  - ParameterKey: InfrastructureBucket
    ParameterValue: BUCKET_URL_PLACEHOLDER
  - ParameterKey: PublicEcrImageUri
    ParameterValue: 063695377715.dkr.ecr.eu-west-1.amazonaws.com/parallelcluster-ui:latest
  #    PublicEcrImageUri can be a repository in:
  #      * Public ECR: must be used when deploying a released image. For this type, use the value:
  #        public.ecr.aws/pcm/parallelcluster-ui:latest
  #      * Private ECR: must be used when deploying a local image for testing. For this type, adapt and use the value:
  #        ACCOUNT_ID.dkr.ecr.REGION.amazonaws.com/parallelcluster-ui:latest
  - ParameterKey: UserPoolId
    UsePreviousValue: true
  - ParameterKey: UserPoolAuthDomain
    UsePreviousValue: true
  - ParameterKey: SNSRole
    UsePreviousValue: true
  - ParameterKey: ImageBuilderVpcId
    UsePreviousValue: true
  - ParameterKey: ImageBuilderSubnetId
    UsePreviousValue: true
  - ParameterKey: VpcEndpointId
    UsePreviousValue: true
  - ParameterKey: LambdaSubnetIds
    UsePreviousValue: true
  - ParameterKey: LambdaSecurityGroupIds
    UsePreviousValue: true
  - ParameterKey: PermissionsBoundaryPolicy
    UsePreviousValue: true
  - ParameterKey: PermissionsBoundaryPolicyPCAPI
    UsePreviousValue: true
  - ParameterKey: IAMRoleAndPolicyPrefix
    UsePreviousValue: true
Capabilities:
  - CAPABILITY_AUTO_EXPAND
  - CAPABILITY_NAMED_IAM
DisableRollback: false
